import groq from 'groq';
import { clientGROQ } from '../client';

// Get one Place by language and slug
export const getOnePlace = async ({ lang, slug }) => {
  const fallbackLang = lang === 'de' ? 'en' : lang;

  const query = groq`*[
    _type == "Place"
    && noLandingPage != true
    && defined(geopoint)
    && (locSlug[$lang].current == $slug || locSlug[$fallbackLang].current == $slug)
    && !(_id in path('drafts.**'))
  ][0]{
    ...,
    "mainImagePublicId": image.public_id,
    region->{
      _id,
      locSlug,
      slug,
      locTitle,
      title,
      howToGetTherePage->{_id, locTitle, locSlug},
    },
    geopoint,
    // * Attractions
    noLandingPage,
    subscriberRegions[]->{
      _id,
      locSlug,
      locTitle,
    },
    attractionLevels {
      isNationalAttraction,
      level->{
        _id,
        priority,
        locSlug,
        locTitle,
      },
    },
    subscriberAttractions[@->.noLandingPage != true && defined(@->.geopoint)]->{
      _id,
      locSlug,
      locTitle,
      locShortDescription,
      "mainImagePublicId": image.public_id,
      "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
    },
    placeCategory->{_id, locTitle, locSlug},

    // * Highlighted places
    highlightedPlaces {
      locTitle,
      locDescription,
      relevantPlaces[@->.noLandingPage != true && defined(@->.geopoint)]->{
        _id,
        locShortDescription,
        locSlug,
        locTitle,
        title,
        "mainImagePublicId": image.public_id,
        "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
      },
      locHighlightedPlaces {
        no[@->.noLandingPage != true && defined(@->.geopoint)]->{
          _id,
          locShortDescription,
          locSlug,
          locTitle,
          title,
          "mainImagePublicId": image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        },
        en[@->.noLandingPage != true && defined(@->.geopoint)]->{
          _id,
          locShortDescription,
          locSlug,
          locTitle,
          title,
          "mainImagePublicId": image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        },
        de[@->.noLandingPage != true && defined(@->.geopoint)]->{
          _id,
          locShortDescription,
          locSlug,
          locTitle,
          title,
          "mainImagePublicId": image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        },
      },
    },

    highlightedArticles {
      ...,
      relevantArticles[0..3]->{
        _id,
        _type,
        articleCategory->,
        cloudinaryImages[0..0],
        coverImage,
        locShortDescription,
        slug,
        locSlug,
        title,
        locTitle,
        geopoint,
        region->{
          _id,
        },
      },
      locHighlightedArticles{
        no[0..3]->{
          _id,
          _type,
          articleCategory->,
          cloudinaryImages[0..0],
          coverImage,
          locShortDescription,
          locSlug,
          locTitle,
          slug,
          title
        },
        en[0..3]->{
          _id,
          _type,
          articleCategory->,
          cloudinaryImages[0..0],
          coverImage,
          locShortDescription,
          locSlug,
          locTitle,
          slug,
          title
        },
        de[0..3]->{
          _id,
          _type,
          articleCategory->,
          cloudinaryImages[0..0],
          coverImage,
          locShortDescription,
          locSlug,
          locTitle,
          slug,
          title
        },
      }
    },
    highlightedActivities {
      ...,
      relevantActivities[0...3]->{
        _id,
        _type,
        address,
        cloudinaryImages[0...0],
        "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
        "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
        contactPoint,
        category->,
        certificates,
        contactPoint,
        externalSystems,
        facilities[]->{..., facility->},
        fromPrice,
        geoDistancePlace,
        geopoint,
        geopointZoom,
        region->{
          _id,
        },
        images[0...0],
        locShortDescription,
        locSlug,
        locTitle,
        place->{
          _id,
          title,
          locTitle,
          slug,
          locSlug,
          geopoint,
          region->{
            _id,
          },
        },
        slug,
        title,
        description,
      },
      locHighlightedActivities {
        no[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          category->,
          certificates,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
        en[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          category->,
          certificates,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
        de[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          category->,
          certificates,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
      }
    },
    highlightedServices {
      ...,
      relevantServices[0...3]->{
        _id,
        _type,
        address,
        cloudinaryImages[0...0],
        "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
        "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
        category->,
        contactPoint,
        externalSystems,
        facilities[]->{..., facility->},
        fromPrice,
        geoDistancePlace,
        geopoint,
        geopointZoom,
        images[0...0],
        locShortDescription,
        locSlug,
        locTitle,
        place->{
          _id,
          title,
          locTitle,
          slug,
          locSlug,
          geopoint,
        },
        slug,
        title,
        description,
      },
      locHighlightedServices{
        no[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          category->,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
        en[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          category->,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
        de[0...3]->{
          _id,
          _type,
          address,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          category->,
          contactPoint,
          externalSystems,
          facilities[]->{..., facility->},
          fromPrice,
          geoDistancePlace,
          geopoint,
          geopointZoom,
          images[0...0],
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
        },
      },
    },
    highlightedEvents {
      ...,
      relevantEvents[0...3]->{
        _id,
        _type,
        address,
        category->,
        cloudinaryImages[0...0],
        "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
        "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
        "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
        contactPoint,
        externalSystems,
        fromPrice,
        geoDistancePlace,
        geopoint,
        image,
        locShortDescription,
        locSlug,
        locTitle,
        place->{
          _id,
          title,
          locTitle,
          slug,
          locSlug,
          geopoint,
        },
        slug,
        title,
        description,
        isEvent,
        event,
      },
      locHighlightedEvents {
        no[0...3]->{
          _id,
          _type,
          address,
          category->,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          externalSystems,
          fromPrice,
          geoDistancePlace,
          geopoint,
          image,
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
          isEvent,
          event,
        },
        en[0...3]->{
          _id,
          _type,
          address,
          category->,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          externalSystems,
          fromPrice,
          geoDistancePlace,
          geopoint,
          image,
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
          isEvent,
          event,
        },
        de[0...3]->{
          _id,
          _type,
          address,
          category->,
          cloudinaryImages[0...0],
          "mainImagePublicId": cloudinaryImages[mainImage == true][0].image.public_id,
          "fallbackImagePublicId": cloudinaryImages[][0].image.public_id,
          "imageSecureUrl": cloudinaryImages[][0].image.secure_url,
          contactPoint,
          externalSystems,
          fromPrice,
          geoDistancePlace,
          geopoint,
          image,
          locShortDescription,
          locSlug,
          locTitle,
          place->{
            _id,
            title,
            locTitle,
            slug,
            locSlug,
            geopoint,
          },
          slug,
          title,
          description,
          isEvent,
          event,
        },
      }
    },
}`;
  return clientGROQ.fetch(query, { lang, slug, fallbackLang });
};
