name: Tests Unit
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test_unit:
    runs-on: ubuntu-latest
    name: Jest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: something-something
      - name: Install dependencies
        run: |
          yarn setup
      - name: Run unit tests
        run: |
          TZ=Europe/Berlin yarn test:ci
